/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bank;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class SimulationTable extends javax.swing.JFrame {

    /**
     * Creates new form SimulationTable
     */
    ArrayList<Customer> Customers = new ArrayList<>();
    String[][] TwoDimensionalCustomerArray;
    String S;
    public SimulationTable() {
        initComponents();

    }

    public SimulationTable(ArrayList<Customer> Customers , String s) {
        initComponents();
        this.Customers = Customers;
        this.S = s;
        TwoDimensionalCustomerArray = new String[Customers.size()][11];

        for (int i = 0; i < Customers.size(); i++) {

            TwoDimensionalCustomerArray[i][0] = String.valueOf(Customers.get(i).CustomerID);
            TwoDimensionalCustomerArray[i][1] = String.valueOf(Customers.get(i).r);
            TwoDimensionalCustomerArray[i][2] = String.valueOf(Customers.get(i).interarrivalTime);
            TwoDimensionalCustomerArray[i][3] = String.valueOf(Customers.get(i).arrivalTime);
            TwoDimensionalCustomerArray[i][4] = String.valueOf(Customers.get(i).serviceTime);
            TwoDimensionalCustomerArray[i][5] = String.valueOf(Customers.get(i).timeServiceBegins);
            TwoDimensionalCustomerArray[i][6] = String.valueOf(Customers.get(i).waitingTime);
            TwoDimensionalCustomerArray[i][7] = String.valueOf(Customers.get(i).timeServiceEnds);
            TwoDimensionalCustomerArray[i][8] = String.valueOf(Customers.get(i).timeSpentInSystem);
            TwoDimensionalCustomerArray[i][9] = String.valueOf(Customers.get(i).idleTime);
            TwoDimensionalCustomerArray[i][10] = (Customers.get(i).TellerType);

        }

        jTable1.setModel(new DefaultTableModel(TwoDimensionalCustomerArray, new String[]{"CustomerID", "RandomDigit", "Interarrival", "arrivalTime", "serviceTime", "timeServiceBegins", "waitingTime", "timeServiceEnds",
            "timeSpentInSystem", "idleTime", "TellerType"}));
        
        TextA.setText(S);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TextA = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, null, null));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE))
                .addContainerGap(860, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(TextA, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea TextA;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
